# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  Default
  
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Mstest_Core.sln'

- task: VSTestWithTypemock@9
  inputs:
    testAssembly: 'bin\Debug\netcoreapp3.1\Mstest_Core.dll'
    logMocking: true
    vsTestVersion: 'latest'
    autoDeployEnabled: false
    licenseName: 'bruno@appointmaster.com'
    licenseKey: '07D5-AC9U-8OA7-AC0C-1B3F'